name: Deploy GitHub Pages

on:
  push:
    branches: [ main ] # 你的源码主分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出源码
        uses: actions/checkout@v4

      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: 安装 pnpm
        run: corepack enable && corepack prepare pnpm@latest --activate

      - name: 安装依赖
        run: pnpm install

      - name: 项目打包构建
        run: pnpm build

      - name: 部署到 pages 分支
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # 你的打包输出文件夹，vue/vite一般是dist
          publish_branch: pages # 部署目标分支
